### ISSUE TITLE
Running Issues

### ISSUE THREAD

**Issue by dyabel** [xxxiaol/GCI#1]
ERROR:root:No stemmer available for 'zh' language -> fall back to porter.
Thank you for your amazing work! Could you help me figure out the possible cause of this error. Thx.

**Comment by xxxiaol** [comment]
Thanks for appreciating our work!
Could you please provide more detailed error log? Like in which line of which file the error occurs.

**Comment by cindyhi** [comment]
I also has this question. 
At fist, it is TypeError, with the following prompt:

File "gci.py", line 144, in count_df_accu
    extractor.candidate_selection(n=1, stoplist=stop_words)
  File "/home/jychen/GCI/yake_modified.py", line 97, in candidate_selection
    self.candidate_filtering(stoplist=list(string.punctuation), minimum_length=1, minimum_word_size=1)
TypeError: candidate_filtering() got an unexpected keyword argument 'stoplist'

We dont't find the code about candidate_filetering, so we just remove the line 97 in yake_modified.py, then we get multiple error:
ERROR:root:No stemmer available for 'zh' language -> fall back to porter.
ERROR:root:No stemmer available for 'zh' language -> fall back to porter.

**Comment by xxxiaol** [comment]
Thanks for the detailed information. The error occurs because the pke package updates and does not support Chinese currently. 
Please reinstall pke with previous commit https://github.com/boudinfl/pke/commit/0729bca0d37ff30fe9d98c2d04304ad0d30465c4 .

**Comment by cindyhi** [comment]
Thanks for your quick reply,  i  will try this version.

**Comment by dyabel** [comment]
![image](https://user-images.githubusercontent.com/52541024/167365260-11ae54dc-5192-47bd-b8ab-65764c10d192.png)
Hi, I have used the same version of pke as yours. And here is another issue, do you know why this occurs?

**Comment by cindyhi** [comment]
I have the same issue. 
![屏幕截图 2022-05-10 222743](https://user-images.githubusercontent.com/42988906/167652954-e7d18bd8-76cf-48d9-a959-3ce76058b546.png)

**Comment by xxxiaol** [comment]
This is because in newer versions of dowhy, identified_estimand.backdoor_variables will output a dict like `{'backdoor1': ['w0'], 'backdoor2': ['w0'], 'backdoor': ['w0']}` instead of a list `['w0']`.
To solve the issue, you can either downgrade dowhy to version 0.2, 
or replace `confounders = identified_estimand.backdoor_variables` to `confounders = identified_estimand.backdoor_variables['backdoor']`. 
(I prefer the first method, as I don't know whether there are further inconsistencies between different versions.)

**Comment by dyabel** [comment]
> This is because in newer versions of dowhy, identified_estimand.backdoor_variables will output a dict like `{'backdoor1': ['w0'], 'backdoor2': ['w0'], 'backdoor': ['w0']}` instead of a list `['w0']`. To solve the issue, you can either downgrade dowhy to version 0.2, or replace `confounders = identified_estimand.backdoor_variables` to `confounders = identified_estimand.backdoor_variables['backdoor']`. (I prefer the first method, as I don't know whether there are further inconsistencies between different versions.)
Thx. There is a warning about nltk, is it important. BTW, what is the version of nltk you used?
![image](https://user-images.githubusercontent.com/52541024/167968050-301f6697-dd41-4f0b-832a-05fa74ce9c16.png)

**Comment by dyabel** [comment]
And how can I see what fact each of the nodes e.g. x50 refers to? Thx.

**Comment by xxxiaol** [comment]
I use NLTK 3.5, and you can provide a list of Chinese stopwords to NLTK.

**Comment by joye322** [comment]
> Thanks for the detailed information. The error occurs because the pke package updates and does not support Chinese currently. Please reinstall pke with previous commit [boudinfl/pke@0729bca](https://github.com/boudinfl/pke/commit/0729bca0d37ff30fe9d98c2d04304ad0d30465c4) .

I also have the same issue. And I have reinstalled the pke  but cannot solve the problem. Can u tell me the solution for this problmm ?
