### ISSUE TITLE
No stemmer for 'zh' language

### ISSUE THREAD

**Issue by clytiiiix** [xxxiaol/GCI#10]
The warning occurs when I run the gci.py.
No stemmer for 'zh' language.
Stemming will not be applied.

**Comment by xxxiaol** [comment]
This occurs because the pke package updates and does not support Chinese currently.
Please reinstall pke with previous commit [https://github.com/boudinfl/pke/commit/0729bca0d37ff30fe9d98c2d04304ad0d30465c4](url).

**Comment by clytiiiix** [comment]
> This occurs because the pke package updates and does not support Chinese currently. Please reinstall pke with previous commit [https://github.com/boudinfl/pke/commit/0729bca0d37ff30fe9d98c2d04304ad0d30465c4](url).

This page can't be found.

**Comment by xxxiaol** [comment]
> > This occurs because the pke package updates and does not support Chinese currently. Please reinstall pke with previous commit [https://github.com/boudinfl/pke/commit/0729bca0d37ff30fe9d98c2d04304ad0d30465c4](url).
> 
> This page can't be found.

Could you try this [link](https://github.com/boudinfl/pke/commit/0729bca0d37ff30fe9d98c2d04304ad0d30465c4)?

**Comment by clytiiiix** [comment]
Thank you! I'll try it.
