### ISSUE TITLE
About warnings

### ISSUE THREAD

**Issue by pipijiev12** [xxxiaol/GCI#11]
The following warning appears when running the gci.py file
WARNING:root:No stemmer available in pke for 'zh' language -> falling back to porter stemmer.
WARNING:root:No stoplist available in pke for 'zh' language.

Without stopword lists and stemmers, what are the subsequent requirements for the dataset this project handles?

**Comment by pipijiev12** [comment]
Can you provide the package of your requirement?

**Comment by xxxiaol** [comment]
This occurs because the pke package updates and does not support Chinese currently.
Please reinstall pke with [the previous commit ](https://github.com/boudinfl/pke/commit/0729bca0d37ff30fe9d98c2d04304ad0d30465c4).
