### ISSUE TITLE
https://ai.tencent.com/ailab/nlp/embedding.html该网站无法登入

### ISSUE THREAD

**Issue by PolarisRisingWar** [xxxiaol/GCI#2]
如题，我现在使用浏览器登入该网站会出现如下问题：
![image](https://user-images.githubusercontent.com/48322321/174014620-14f3c5dc-b874-4451-b307-2a81668ed817.png)
无法正常进入网站。想请问这一现象是暂时的还是该网站已经失效？如果该网站已经失效的话，请问对应的文件您这边还能否提供呢？
麻烦您了，谢谢！

**Comment by xxxiaol** [comment]
您好，
该网站更改了地址，您可以从https://ai.tencent.com/ailab/nlp/en/data/tencent-ailab-embedding-zh-d200-v0.2.0.tar.gz 下载
