### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by 1633232731** [xxxiaol/GCI#3]
多谢分享！
有一个问题，我使用data.json文件发现案件的数量和论文中的似乎不一致，例如下图所示，在data.json文件中 **故意伤害** 有5006个，但是在论文中有6377个，是不是我哪里没有考虑到？多谢 
我已经尝试过了将训练集验证集测试集都计算在内，但是这样案件数量就会多于论文的数量。同时我注意到论文中好像要去掉多项罪名，但是在data.json中仍然存在多项罪名的数据，我尝试将这些数据过滤掉后，总的数量又会小于论文所示的数量。以上的数量都只是说 **故意伤害** 这一个罪名
![image](https://user-images.githubusercontent.com/58805028/176365417-dfb00965-c8aa-4977-b091-513fdaa494f8.png)
![image](https://user-images.githubusercontent.com/58805028/176365468-86fa2ef4-410a-4fa0-bb29-31e6c6ac0823.png)

**Comment by xxxiaol** [comment]
感谢您对我们工作的关注！
我们的数据集包含了多罪名数据（剔除了多个罪名中同时包含超过一个需要辨析的罪名的）。比如辨析贪污和挪用公款罪时，罪名中同时包含贪污罪和诈骗罪的案件会被保留，而同时包含贪污罪和挪用公款罪的会被排除。

**Comment by 1633232731** [comment]
多谢，问题解决了~！
