### ISSUE TITLE
Py-Causal

### ISSUE THREAD

**Issue by ruarua6666** [xxxiaol/GCI#4]
您好，我想请问一下去哪里下载Py-Causal呀？
如果是这个链接的：https://github.com/bd2kccd/py-causal，
他要求的是python=3.6,而GCI要求的是3.7以上，冲突了。

**Comment by xxxiaol** [comment]
我是用的这个链接的，它在python 3.7也可以运行

**Comment by ruarua6666** [comment]
好的，感谢您。
