### ISSUE TITLE
cannot install iavabridge via pip

### ISSUE THREAD

**Issue by Kirawang23** [xxxiaol/GCI#5]
pip install javabridge doesn't work:

This is my solution when using pycausal:

 install javabridge before pycausal:
```
sudo apt install openjdk-8-jdk gcc
```
```
pip install git+https://github.com/LeeKamentsky/python-javabridge
```
download pycausal and open setup.py
```
python setup.py install --user
```

**Comment by xxxiaol** [comment]
Thanks for sharing!
