### ISSUE TITLE
Unexpected keyword argument issue

### ISSUE THREAD

**Issue by alexrao02** [xxxiaol/GCI#8]
I just ran this project in Colab and I got this problem:

File "/content/GCI-main/yake_modified.py", line 97, in candidate_selection
    self.candidate_filtering(stoplist=list(string.punctuation), minimum_length=1, minimum_word_size=1)
TypeError: candidate_filtering() got an unexpected keyword argument 'stoplist'

How can I fix it?

**Comment by alexrao02** [comment]
I just delete code that cause error and another there is another problem:

ERROR:root:No stemmer available for 'zh' language -> fall back to porter.

**Comment by xxxiaol** [comment]
Hi Alex, you may take a look at [issue 1](https://github.com/xxxiaol/GCI/issues/1) and install the specific version of pke.

**Comment by alexrao02** [comment]
收到，谢谢。
