### ISSUE TITLE
I changed the version of PKE, but something went wrong

### ISSUE THREAD

**Issue by alexrao02** [xxxiaol/GCI#9]
I run the version https://github.com/boudinfl/pke/commit/0729bca0d37ff30fe9d98c2d04304ad0d30465c4 in colab.
And I get this error:

LookupError: Can't find any language named 'hinglish'

I didn't encounter this problem when use latest PKE. How can I fix it?

**Comment by alexrao02** [comment]
Have you ever meet this problem? I have worked for it whole day but can't fix it :(

**Comment by xxxiaol** [comment]
Could you provide the full error message? Like the error occurs on which line of the code.

**Comment by alexrao02** [comment]
OK. I take two screenshots. The problem is that if I use the latest PKE(install directly by pip) I will encounter issue like Pic1; And if I use PKE you gave, I will encounter issue like Pic2. It's a little bit embarrassed and I don't know how to fix it.  

PS: I have tried changing the version of Python but it didn't work...

![](https://raw.githubusercontent.com/alexrao02/ImageHost/main/IMG_9548.JPG)
![](https://raw.githubusercontent.com/alexrao02/ImageHost/main/IMG_9547.JPG)

**Comment by xxxiaol** [comment]
This seems to be a problem of using pke with colab. Please refer to [https://github.com/boudinfl/pke/issues/200](url) and see if removing stopword files in the `nltk_data` folder helps. 
If not, you may consider running the code locally, as running `gci.py` does not require excessive computing resources.
